config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'top' => 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save   # データ（レコード）を削除
      redirect_to book_path(@book.id), notice: "Book was successfully created." # 投稿一覧画面へリダイレクト
    else
      render :new
     # redirect_to books_path, alert: "Create was failed" # 投稿一覧画面へリダイレクト
    end
  end
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])

  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if  @book.update(book_params)  # データ（レコード）を削除
      redirect_to book_path(@book.id), notice: "Book was successfully updated." # 投稿一覧画面へリダイレクト
    else
      render :new
      #redirect_to books_path, alert: "Update was failed" # 投稿一覧画面へリダイレクト
    end
  end
  def destroy
    @book = Book.find(params[:id])  # データ（レコード）を1件取得
    if @book.destroy   # データ（レコード）を削除
      redirect_to books_path, notice: "Book was successfully destroyed." # 投稿一覧画面へリダイレクト
    else
      render :new
      #redirect_to books_path, alert: "Destroy was failed" # 投稿一覧画面へリダイレクト
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def succsess_or_not
    true
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end

  def top
  end
  def index

  end

  def show
  end



  def edit
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %><br>
  <%= f.submit 'Update Book' %><br>
  <%=link_to "Show", @book%>
  <%= link_to "Back", "/books" %>
<% end %>

app/views/books/index.html.erb
<%= notice %>
<%= alert %>
<h1>Books</h1>
<table>
  <tr>
    <th>Title </th>
    <th>Body </th>
  </tr>
<% @books.each do |book| %>
  <tr>
    <td><%=book.title%></td>
    <td><%=book.body %></td><td>
    <td><%=link_to "Show", book%></td>
    <td><%=link_to "Edit", edit_book_path(book) %></td>
    <td><%=link_to "Destroy",  destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
  </table>

<h1>New Book</h1>
<!-- form_with部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>Errors</h1>
<!-- form_with部分 -->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occured.<br>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %><br>

<%= link_to "Back", "/books" %>

app/views/books/show.html.erb
<%= notice %>
<%= alert %>
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", "/books" %>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<!-- form_with部分 -->

<% end %>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/homes/top.html.erb
<h1>
  ようこそBookersヘ！
</h1>
 <p>
  Bookerでは、さまざまな書籍に関するあなたの意見や<br>
  印象を共有し好感することができます
 </p>
 <p><%= link_to "start", books_path %></p>
 <span>

 </span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>